# Generated by Django 4.2.4 on 2023-10-23 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_apis', '0002_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='iniUser',
        ),
    ]
