# Generated by Django 4.2.4 on 2023-10-23 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_apis', '0003_rename_user_iniuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='iniUser',
            new_name='user',
        ),
    ]
