# Generated by Django 4.2.4 on 2023-10-26 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_apis', '0004_rename_iniuser_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
